### ISSUE TITLE
WikiExport header 

### ISSUE THREAD

**Issue by Traap** [lervag/wiki.vim#138]
WikiExport to PDF work fine.

Is there an *easy* way to have the wiki-page written to the header or footer.   

The PDF document has the page number in the footer.

**Comment by lervag** [comment]
Well, no, sorry - not any that I'm currently aware of. I won't mind adding something like this, but I'm not fully sure how. The export mechanism is based on pandoc. Perhaps something like [this](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html%23raw-tex#Metadata_blocks) can be helpful?

**Comment by Traap** [comment]
[Pandoc's User Guide
mentions](https://pandoc.org/MANUAL.html#option--include-in-header) describes
*--template* and *--meta-file* options.  The bash script and wiki.yaml
(meta-file) were used generate the attached pdf.

```bash
pandoc \
  --standalone \
  --template=default.latex \
  -f markdown \
  --metadata-file=wiki.yaml \
  -o pandoc/index.pdf index.wiki 
```

[Pandoc Template for Creating Trivadis CI like documentation](https://github.com/oehrls/pandoc_template) was helped understand meta files.   
```yaml
title: "index.wiki"
subtitle: "wiki page file name"
author: "Gary A. Howard"
date: "2021-03-22"
tvddocversion: 0.9
papersize: a4
titlepage: true
pagestyle: headings
toc: true
toc-own-page: true
toc-title: Table of Contents
numbersections: true
thanks: "Karl Yngve Lervåg"
mainfont: Nunito Sans SemiBold
monofont: Courier New
```
[index.pdf](https://github.com/lervag/wiki.vim/files/6186924/index.pdf)
